In [13]:
import numpy as np

In [14]:
# QUBITS

# qubit in |0> state, 100% probability of measuring 0
q0 = [1, 0]

# qubit in |1> state, 100% probability of measuring 1
q1 = [0, 1]

# qubit |+>, superposition, 50% probability measuring 0, 50% probability measuring 1
q2 = [0.7071067811865475, 0.7071067811865475]

# qubit |->, superposition, 50% probability measuring 0, 50% probability measuring 1 with phase pi
q3 = [0.7071067811865475, -0.7071067811865475]

# qubit |i>, superposition, 50% probability measuring 0, 50% probability measuring 1 with phase pi/2
q4 = [0.7071067811865475, 0 + 0.7071067811865475j]

# qubit |-i>, superposition, 50% probability measuring 0, 50% probability measuring 1 with phase -pi/2
q5 = [0.7071067811865475, 0 - 0.7071067811865475j]

In [16]:
p4 = np.abs(q4)**2
print(p4)

[0.5 0.5]


In [17]:
# State Vector
# combined state of multiple qubits is the tensor product
q0q1 = np.kron(q0, q1)
print(q0q1)

[0 1 0 0]


In [18]:
# Quantum Gates
print("Initial state:\t", q0)
X = np.array([
    [0, 1],
    [1, 0]
])
# matrix-vector dot product
fn = np.dot(X, q0)
print("Final state:\t", fn)

Initial state:	 [1, 0]
Final state:	 [0 1]


In [21]:
# Matrix Operator
# 'resizing' a gate-matrix to the dimension of the state vector
# e.g. a matrix operator for X gate acting on 3-qubit state vector

psi = [1, 0, 0, 0, 0, 0, 0, 0]
print("Initial state:\t", psi)
# define X-gate
X = np.array([
    [0, 1],
    [1, 0]
])
# define 2 x 2 identity matrix
I = np.identity(2)
# calculate operator for X-gate acting on third qubit in 3-qubit circuit
O = np.kron(np.kron(I, I), X)
print("\nOperator:\n\n", O, "\n")
psi =  np.dot(psi, O)
print("Final state:\t", psi)

Initial state:	 [1, 0, 0, 0, 0, 0, 0, 0]

Operator:

 [[0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]] 

Final state:	 [0. 1. 0. 0. 0. 0. 0. 0.]


In [23]:
# Simulator program

def get_ground_state(num_qubits):
    # return vector of size 2**num_qubits with all zeroes except first element which is 1
    return

def get_operator(total_qubits, gate_unitary, target_qubits):
    # return unitary operator of size 2**n x 2**n for a given gate and target qubits
    return

def run_program(initial_state, program):
    # read program and for each gate:
    #   - calculate matrix operator
    #   - multiply state with operator
    # return final state
    return

def measure_all(state_vector):
    # choose element from state_vector using weighted random and return it's index
    return

def get_counts(state_vector, num_shots):
    # simply execute measure_all in a loop num_shots times and
    # return object with statistics in the following form
    #  {
    #      element_index: number_of_ocurrences,
    #      element_index: number_of_ocurrences,
    #      element_index: number_of_ocurrences,
    #      ...
    #  }
    # (only for elements which occurred - returned from measure_all)
    return
    